version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - my-network
    hostname: backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - my-network
    depends_on:
      - backend

networks:
  my-network:
    driver: bridge
